another pep exception
GameAnalytics/python-style-guide pull request #5
Opened 2022-05-02 11:27 UTC by agnesk92

2022-05-09 13:09 UTC, cristianbercu requested changes

2022-05-09 13:09 UTC, cristianbercu commented on README.md
> +    - functions with long argument list should prefer [Black style](https://github.com/psf/black/issues/1178)
If I am understanding this correctly, you want to recommend that a function like this:

```python
def sum(a: int, b: int ... , x: int) -> None:
    return a + b + .. + x
```

should be styled like this:
```python
def sum(
    a: int,
    b: int,
    ... ,
    x: int
) -> None:
    return a + b + .. + x
```

Makes sense 👍🏼 . However, the guideline is for lecturing and ideally, any reader shouldn't be redirected to another webpage to make sense of it. Think of it as a scientific article where every statement backed by another scientific reading is re-iterated by the author(s), marked with a superscript number, and referenced in the end; take Wikipedia as an example.

I think it's best if you provide here an example of what is the black style for a long argument list and not reference the Github issue, but the Black documentation.

2022-05-09 13:09 UTC, cristianbercu commented on README.md
> +1. PEP8 is **law**, never break PEP8. Only exceptions:
```suggestion
1. PEP8 is **law**, never break PEP8. The only exceptions are:
```

😄

2022-05-09 13:24 UTC, cristianbercu commented on README.md
> +    - functions with long argument list should prefer [Black style](https://github.com/psf/black/issues/1178)
We violate it which is why you point it out as an exception. Isn't that what you are trying to say here??

_functions with long argument list should prefer Black style_

2022-05-10 10:39 UTC, cristianbercu requested changes
I don't see any changes here, not sure why re-requesting a review. In the comments, there's not enough information to support an entry to the guideline

2022-05-10 11:53 UTC, agnesk92 commented
> I don't see any changes here, not sure why re-requesting a review. In the comments, there's not enough information to support an entry to the guideline

https://github.com/GameAnalytics/python-style-guide/pull/5/commits/e2f426dfe1aefd076b271ca4c588c9d812bca4ed

2022-05-10 12:04 UTC, cristianbercu approved these changes

2022-05-10 12:07 UTC, merged